version: '3.8'
services:
  db-local:
    image: postgres:16.4-alpine3.19
    container_name: shortener-url-db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: blizzard
    ports:
      - 5432:5432
    volumes:
      - ./postgres-local/data:/var/lib/postgresql/data
    networks:
      - local-app-network-shortener-url
networks:
  local-app-network-shortener-url:
    name: local-app-network-shortener-url #definir nome da rede sem pegar tambem o nome da pasta
    driver: bridge