global:
  scrape_interval: 15s
  scrape_timeout: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: shortener-api
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - shortener-url-api:3000