export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const SHORT_URLS_REPOSITORY = 'SHORT_URLS_REPOSITORY';
export const REDIS_CLIENT = 'REDIS_CLIENT';
export const REDIS_REPOSITORY = 'REDIS_REPOSITORY';
